#region Using
using Orchard.ContentManagement.Handlers;
using Orchard.Environment.Extensions;
using Yaplex.SEO.Models;
#endregion

namespace Yaplex.SEO.Handlers {
    [OrchardFeature("Yaplex.SEO.Robots")]
    public class RobotsSettingsPartHandler : ContentHandler {
        public RobotsSettingsPartHandler() {
            Filters.Add(new ActivatingFilter<RobotsSettingsPart>(Constants.SiteContentTypeName));
            OnActivated<RobotsSettingsPart>(SetupLazyFields);
        }

        #region Methods
        private static string CreateDefaultRobotsContent() {
            return $"# robots.txt generated by Yaplex.SEO (https://yaplex.com) at {Constants.DomainMarker}\r\nUser-agent: *\r\nDisallow: \r\n";
        }

        private static void SetupLazyFields(ActivatedContentContext context, RobotsSettingsPart part) {
            part.DefaultRobotsContent.Loader(CreateDefaultRobotsContent);
        }
        #endregion
    }
}
