#region Using
using Orchard;
using Orchard.ContentManagement;
using Orchard.ContentManagement.Handlers;
using Orchard.Environment.Extensions;
using Orchard.Localization;
using Yaplex.SEO.Models;
#endregion

namespace Yaplex.SEO.Handlers {
    [OrchardFeature("Yaplex.SEO.Robots")]
    public class RobotsSettingsPartHandler : ContentHandler {
        private readonly IOrchardServices _orchardServices;

        public RobotsSettingsPartHandler(IOrchardServices orchardServices) {
            _orchardServices = orchardServices;
            T = NullLocalizer.Instance;
            Filters.Add(new ActivatingFilter<RobotsSettingsPart>("Site"));
            OnActivated<RobotsSettingsPart>(SetupLazyFields);
        }

        #region Properties
        public Localizer T { get; set; }
        #endregion

        #region Methods
        protected override void GetItemMetadata(GetContentItemMetadataContext context) {
            if (context.ContentItem.ContentType != "Site") {
                return;
            }
            base.GetItemMetadata(context);
            context.Metadata.EditorGroupInfo.Add(new GroupInfo(T(Constants.AdminMenuName)) {
                Position = "1"
            });
        }

        private string CreateDefaultRobotsContent() {
            var baseUrl = _orchardServices.WorkContext.CurrentSite.BaseUrl;
            return $"# robots.txt generated by Yaplex.SEO (https://yaplex.com) at {baseUrl}\r\nUser-agent: *\r\nDisallow: \r\n";
        }

        private void SetupLazyFields(ActivatedContentContext context, RobotsSettingsPart part) {
            part.DefaultRobotsContent.Loader(CreateDefaultRobotsContent);
        }
        #endregion
    }
}
