using System;
using System.Linq;
using System.Web.Mvc;
using Orchard;
using Orchard.ContentManagement.Handlers;
using Orchard.Core.Common.Utilities;
using Orchard.Environment.Extensions;
using Orchard.Environment.Extensions.Models;
using Orchard.Environment.Features;
using Orchard.Mvc.Extensions;
using Yaplex.SEO.Models;

namespace Yaplex.SEO.Handlers
{
    [OrchardFeature("Yaplex.SEO.Robots")]
    public class RobotsSettingsPartHandler : ContentHandler
    {
        private readonly IFeatureManager _featureManager;
        private readonly IOrchardServices _orchardServices;
        private readonly UrlHelper _urlHelper;

        public RobotsSettingsPartHandler(IOrchardServices orchardServices, IFeatureManager featureManager,
            UrlHelper urlHelper)
        {
            _orchardServices = orchardServices;
            _featureManager = featureManager;
            _urlHelper = urlHelper;
            Filters.Add(new ActivatingFilter<RobotsSettingsPart>(new []{ "Site"}));
            OnActivated<RobotsSettingsPart>(SetupLazyFields);
        }

        private void SetupLazyFields(ActivatedContentContext context, RobotsSettingsPart part)
        {
            part.DefaultRobotsContent.Loader(CreateDefaultRobotsContent);
        }

        private string CreateDefaultRobotsContent()
        {
            var baseUrl = _orchardServices.WorkContext.CurrentSite.BaseUrl;
            return string.Format("# robots.txt generated by Yaplex.SEO (https://yaplex.com) at {0}\r\nUser-agent: *\r\nDisallow: \r\n", baseUrl);
        }
    }
}